name: Foo
on:
  pull_request:
    paths:
      - 'frontend/**'
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
jobs:
  job:    
    runs-on: ubuntu-latest
    steps:
      - run: env
